name: Lint 🧶

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Lint:
    name: SuperLinter 🦸🏻‍♀️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 🛎
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Lint Code Base 🕵🏻‍♀️
        uses: super-linter/super-linter/slim@1fa6ba58a88783e9714725cf89ac26d53e80c148 # v6
        env:
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITLEAKS: true
          DEFAULT_BRANCH: main
          VALIDATE_JSON: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  GoLint:
    name: Lint Go Code 🔍
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.22.1
    steps:
      - name: Checkout Repo 🛎
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Go 🐹
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint Go Code 🕵🏻‍♂️
        uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4
        with:
          version: latest
          only-new-issues: false
